# config/_default/menus.en.toml

# Main header navigation
[[main]]
  name    = "About"
  pageRef = "about"
  weight  = 10

[[main]]
  name    = "Projects"
  pageRef = "projects"
  weight  = 20

[[main]]
  name    = "Experience"
  pageRef = "experience"
  weight  = 30

[[main]]
  name = "ResumeÃÅ"
  url = "/resume"
  weight = 40
  [main.params]
    target = "_blank"

[[main]]
  name    = "Blog"
  pageRef = "posts"
  weight  = 50

[[main]]
  name = "GitHub"
  url = "https://github.com/ravellaabhinav"
  weight = 88
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# Optional footer links

